### ISSUE TITLE
update requirements.txt - API breaking changes coming to fastKDE

### ISSUE THREAD

**Issue by taobrienlbl** [igmmgi/pydmc#1]
API-breaking changes are coming to fastkde (see [this PR](https://github.com/LBL-EESA/fastkde/pull/26)).  I see that `requirements.txt` has fastKDE listed without a version.  I suggest changing this to `fastkde==1.0.30` to ensure that code dependent on fastKDE continues to work.

**Comment by igmmgi** [comment]
thanks
