### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by luc-vermeylen** [igmmgi/pydmc#2]
Dear,

i am trying to install the pydmc package, but run into this problem when trying to import the package in python. I am using a clean miniconda environment (called "pydmc" with python 3.8.18) on my M1 macbook pro:

> (pydmc) luc@MacBook-Pro-van-Luc ~ % python
> Python 3.8.18 (default, Sep 11 2023, 08:17:33) 
> [Clang 14.0.6 ] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pydmc
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/luc/src/pydmc/pydmc/__init__.py", line 1, in <module>
>     from .dmc import Sim, Ob, Fit, Prms, PrmsFit, Plot, PlotFit, flanker_data, simon_data
>   File "/Users/luc/src/pydmc/pydmc/dmc.py", line 1071, in <module>
>     class FitSubjects:
>   File "/Users/luc/src/pydmc/pydmc/dmc.py", line 1077, in FitSubjects
>     def _split_subjects(self) -> list[Fit]:
> TypeError: 'type' object is not subscriptable

Any idea how i can solve this?

Best,
Luc

**Comment by igmmgi** [comment]
Sorry, I can't test this. I do not have access to M1 mac, not am I familiar with miniconda. I just tested a fresh install with a fresh Python environment via pyenv and all seems fine with the install. Maybe update the python version (3.8.18 might not deal with type hints). I did see a comment in my code that I originally tested with 3.9+
